### ISSUE TITLE
PoE power input

### ISSUE THREAD

**Issue by joshschmelzle** [WLAN-Pi/wlanpi-hwtest#15]
Issue for tracking power input via PoE / RJ45

**Comment by jolla** [comment]
Manual check need by tester to visually confirm white LED near ethernet jack is lit when PoE is connected

**Comment by jolla** [comment]
GPIO16 when defined as input pull-up indicates USB type C charger/host connected
0 - connected
1 - not connected (or USB-A power)
If charging = yes && GPIO=1 then PoE is the power input
